# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  ent:
    dir: pkg
    sources:
      - ent/schema/*.go
    generates:
      - ent/*.go
    cmds:
      - ent generate ./ent/schema
    method: checksum
  todo:
    cmds:
      - cat TODO.md
      - rg 'TODO'
  backup:
    cmds:
      - cp sqlite3.db backups
  build:
    deps: ['ent']
    cmds:
      - go build ./cmd/magicman
