// Code generated by entc, DO NOT EDIT.

package deckcard

const (
	// Label holds the string label denoting the deckcard type in the database.
	Label = "deck_card"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCount holds the string denoting the count field in the database.
	FieldCount = "count"
	// EdgeDeck holds the string denoting the deck edge name in mutations.
	EdgeDeck = "deck"
	// EdgeCard holds the string denoting the card edge name in mutations.
	EdgeCard = "card"
	// Table holds the table name of the deckcard in the database.
	Table = "deck_cards"
	// DeckTable is the table that holds the deck relation/edge.
	DeckTable = "deck_cards"
	// DeckInverseTable is the table name for the Deck entity.
	// It exists in this package in order to avoid circular dependency with the "deck" package.
	DeckInverseTable = "decks"
	// DeckColumn is the table column denoting the deck relation/edge.
	DeckColumn = "deck_cards"
	// CardTable is the table that holds the card relation/edge.
	CardTable = "deck_cards"
	// CardInverseTable is the table name for the Card entity.
	// It exists in this package in order to avoid circular dependency with the "card" package.
	CardInverseTable = "cards"
	// CardColumn is the table column denoting the card relation/edge.
	CardColumn = "card_deck_cards"
)

// Columns holds all SQL columns for deckcard fields.
var Columns = []string{
	FieldID,
	FieldCount,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "deck_cards"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"card_deck_cards",
	"deck_cards",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// CountValidator is a validator for the "count" field. It is called by the builders before save.
	CountValidator func(int) error
)
