// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/SethCurry/magicman/pkg/ent/color"
)

// Color is the model entity for the Color schema.
type Color struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ColorQuery when eager-loading is set.
	Edges ColorEdges `json:"edges"`
}

// ColorEdges holds the relations/edges for other nodes in the graph.
type ColorEdges struct {
	// Cards holds the value of the cards edge.
	Cards []*Card `json:"cards,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CardsOrErr returns the Cards value or an error if the edge
// was not loaded in eager-loading.
func (e ColorEdges) CardsOrErr() ([]*Card, error) {
	if e.loadedTypes[0] {
		return e.Cards, nil
	}
	return nil, &NotLoadedError{edge: "cards"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Color) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case color.FieldID:
			values[i] = new(sql.NullInt64)
		case color.FieldName, color.FieldCode:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Color", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Color fields.
func (c *Color) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case color.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			c.ID = int(value.Int64)
		case color.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				c.Name = value.String
			}
		case color.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				c.Code = value.String
			}
		}
	}
	return nil
}

// QueryCards queries the "cards" edge of the Color entity.
func (c *Color) QueryCards() *CardQuery {
	return (&ColorClient{config: c.config}).QueryCards(c)
}

// Update returns a builder for updating this Color.
// Note that you need to call Color.Unwrap() before calling this method if this Color
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Color) Update() *ColorUpdateOne {
	return (&ColorClient{config: c.config}).UpdateOne(c)
}

// Unwrap unwraps the Color entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Color) Unwrap() *Color {
	tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Color is not a transactional entity")
	}
	c.config.driver = tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Color) String() string {
	var builder strings.Builder
	builder.WriteString("Color(")
	builder.WriteString(fmt.Sprintf("id=%v", c.ID))
	builder.WriteString(", name=")
	builder.WriteString(c.Name)
	builder.WriteString(", code=")
	builder.WriteString(c.Code)
	builder.WriteByte(')')
	return builder.String()
}

// Colors is a parsable slice of Color.
type Colors []*Color

func (c Colors) config(cfg config) {
	for _i := range c {
		c[_i].config = cfg
	}
}
