// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SethCurry/magicman/pkg/ent/card"
	"github.com/SethCurry/magicman/pkg/ent/deck"
	"github.com/SethCurry/magicman/pkg/ent/deckcard"
)

// DeckCardCreate is the builder for creating a DeckCard entity.
type DeckCardCreate struct {
	config
	mutation *DeckCardMutation
	hooks    []Hook
}

// SetCount sets the "count" field.
func (dcc *DeckCardCreate) SetCount(i int) *DeckCardCreate {
	dcc.mutation.SetCount(i)
	return dcc
}

// SetDeckID sets the "deck" edge to the Deck entity by ID.
func (dcc *DeckCardCreate) SetDeckID(id int) *DeckCardCreate {
	dcc.mutation.SetDeckID(id)
	return dcc
}

// SetNillableDeckID sets the "deck" edge to the Deck entity by ID if the given value is not nil.
func (dcc *DeckCardCreate) SetNillableDeckID(id *int) *DeckCardCreate {
	if id != nil {
		dcc = dcc.SetDeckID(*id)
	}
	return dcc
}

// SetDeck sets the "deck" edge to the Deck entity.
func (dcc *DeckCardCreate) SetDeck(d *Deck) *DeckCardCreate {
	return dcc.SetDeckID(d.ID)
}

// SetCardID sets the "card" edge to the Card entity by ID.
func (dcc *DeckCardCreate) SetCardID(id int) *DeckCardCreate {
	dcc.mutation.SetCardID(id)
	return dcc
}

// SetNillableCardID sets the "card" edge to the Card entity by ID if the given value is not nil.
func (dcc *DeckCardCreate) SetNillableCardID(id *int) *DeckCardCreate {
	if id != nil {
		dcc = dcc.SetCardID(*id)
	}
	return dcc
}

// SetCard sets the "card" edge to the Card entity.
func (dcc *DeckCardCreate) SetCard(c *Card) *DeckCardCreate {
	return dcc.SetCardID(c.ID)
}

// Mutation returns the DeckCardMutation object of the builder.
func (dcc *DeckCardCreate) Mutation() *DeckCardMutation {
	return dcc.mutation
}

// Save creates the DeckCard in the database.
func (dcc *DeckCardCreate) Save(ctx context.Context) (*DeckCard, error) {
	var (
		err  error
		node *DeckCard
	)
	if len(dcc.hooks) == 0 {
		if err = dcc.check(); err != nil {
			return nil, err
		}
		node, err = dcc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DeckCardMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = dcc.check(); err != nil {
				return nil, err
			}
			dcc.mutation = mutation
			if node, err = dcc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(dcc.hooks) - 1; i >= 0; i-- {
			if dcc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = dcc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dcc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (dcc *DeckCardCreate) SaveX(ctx context.Context) *DeckCard {
	v, err := dcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dcc *DeckCardCreate) Exec(ctx context.Context) error {
	_, err := dcc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcc *DeckCardCreate) ExecX(ctx context.Context) {
	if err := dcc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dcc *DeckCardCreate) check() error {
	if _, ok := dcc.mutation.Count(); !ok {
		return &ValidationError{Name: "count", err: errors.New(`ent: missing required field "DeckCard.count"`)}
	}
	if v, ok := dcc.mutation.Count(); ok {
		if err := deckcard.CountValidator(v); err != nil {
			return &ValidationError{Name: "count", err: fmt.Errorf(`ent: validator failed for field "DeckCard.count": %w`, err)}
		}
	}
	return nil
}

func (dcc *DeckCardCreate) sqlSave(ctx context.Context) (*DeckCard, error) {
	_node, _spec := dcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dcc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (dcc *DeckCardCreate) createSpec() (*DeckCard, *sqlgraph.CreateSpec) {
	var (
		_node = &DeckCard{config: dcc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: deckcard.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: deckcard.FieldID,
			},
		}
	)
	if value, ok := dcc.mutation.Count(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: deckcard.FieldCount,
		})
		_node.Count = value
	}
	if nodes := dcc.mutation.DeckIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deckcard.DeckTable,
			Columns: []string{deckcard.DeckColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: deck.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.deck_cards = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := dcc.mutation.CardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deckcard.CardTable,
			Columns: []string{deckcard.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: card.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.card_deck_cards = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DeckCardCreateBulk is the builder for creating many DeckCard entities in bulk.
type DeckCardCreateBulk struct {
	config
	builders []*DeckCardCreate
}

// Save creates the DeckCard entities in the database.
func (dccb *DeckCardCreateBulk) Save(ctx context.Context) ([]*DeckCard, error) {
	specs := make([]*sqlgraph.CreateSpec, len(dccb.builders))
	nodes := make([]*DeckCard, len(dccb.builders))
	mutators := make([]Mutator, len(dccb.builders))
	for i := range dccb.builders {
		func(i int, root context.Context) {
			builder := dccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeckCardMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dccb *DeckCardCreateBulk) SaveX(ctx context.Context) []*DeckCard {
	v, err := dccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dccb *DeckCardCreateBulk) Exec(ctx context.Context) error {
	_, err := dccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dccb *DeckCardCreateBulk) ExecX(ctx context.Context) {
	if err := dccb.Exec(ctx); err != nil {
		panic(err)
	}
}
