// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/SethCurry/magicman/pkg/ent/card"
	"github.com/SethCurry/magicman/pkg/ent/ruling"
)

// Ruling is the model entity for the Ruling schema.
type Ruling struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Text holds the value of the "text" field.
	Text string `json:"text,omitempty"`
	// Date holds the value of the "date" field.
	Date time.Time `json:"date,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RulingQuery when eager-loading is set.
	Edges        RulingEdges `json:"edges"`
	card_rulings *int
}

// RulingEdges holds the relations/edges for other nodes in the graph.
type RulingEdges struct {
	// Card holds the value of the card edge.
	Card *Card `json:"card,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CardOrErr returns the Card value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RulingEdges) CardOrErr() (*Card, error) {
	if e.loadedTypes[0] {
		if e.Card == nil {
			// The edge card was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: card.Label}
		}
		return e.Card, nil
	}
	return nil, &NotLoadedError{edge: "card"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Ruling) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case ruling.FieldID:
			values[i] = new(sql.NullInt64)
		case ruling.FieldText:
			values[i] = new(sql.NullString)
		case ruling.FieldDate:
			values[i] = new(sql.NullTime)
		case ruling.ForeignKeys[0]: // card_rulings
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Ruling", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Ruling fields.
func (r *Ruling) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ruling.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			r.ID = int(value.Int64)
		case ruling.FieldText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field text", values[i])
			} else if value.Valid {
				r.Text = value.String
			}
		case ruling.FieldDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date", values[i])
			} else if value.Valid {
				r.Date = value.Time
			}
		case ruling.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field card_rulings", value)
			} else if value.Valid {
				r.card_rulings = new(int)
				*r.card_rulings = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryCard queries the "card" edge of the Ruling entity.
func (r *Ruling) QueryCard() *CardQuery {
	return (&RulingClient{config: r.config}).QueryCard(r)
}

// Update returns a builder for updating this Ruling.
// Note that you need to call Ruling.Unwrap() before calling this method if this Ruling
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Ruling) Update() *RulingUpdateOne {
	return (&RulingClient{config: r.config}).UpdateOne(r)
}

// Unwrap unwraps the Ruling entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (r *Ruling) Unwrap() *Ruling {
	tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("ent: Ruling is not a transactional entity")
	}
	r.config.driver = tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Ruling) String() string {
	var builder strings.Builder
	builder.WriteString("Ruling(")
	builder.WriteString(fmt.Sprintf("id=%v", r.ID))
	builder.WriteString(", text=")
	builder.WriteString(r.Text)
	builder.WriteString(", date=")
	builder.WriteString(r.Date.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Rulings is a parsable slice of Ruling.
type Rulings []*Ruling

func (r Rulings) config(cfg config) {
	for _i := range r {
		r[_i].config = cfg
	}
}
