// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/SethCurry/magicman/pkg/ent/deckcard"
	"github.com/SethCurry/magicman/pkg/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	deckcardFields := schema.DeckCard{}.Fields()
	_ = deckcardFields
	// deckcardDescCount is the schema descriptor for count field.
	deckcardDescCount := deckcardFields[0].Descriptor()
	// deckcard.CountValidator is a validator for the "count" field. It is called by the builders before save.
	deckcard.CountValidator = deckcardDescCount.Validators[0].(func(int) error)
}
