// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/SethCurry/magicman/pkg/ent/subtype"
)

// SubType is the model entity for the SubType schema.
type SubType struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubTypeQuery when eager-loading is set.
	Edges SubTypeEdges `json:"edges"`
}

// SubTypeEdges holds the relations/edges for other nodes in the graph.
type SubTypeEdges struct {
	// Cards holds the value of the cards edge.
	Cards []*Card `json:"cards,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CardsOrErr returns the Cards value or an error if the edge
// was not loaded in eager-loading.
func (e SubTypeEdges) CardsOrErr() ([]*Card, error) {
	if e.loadedTypes[0] {
		return e.Cards, nil
	}
	return nil, &NotLoadedError{edge: "cards"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubType) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case subtype.FieldID:
			values[i] = new(sql.NullInt64)
		case subtype.FieldName:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type SubType", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubType fields.
func (st *SubType) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subtype.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			st.ID = int(value.Int64)
		case subtype.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				st.Name = value.String
			}
		}
	}
	return nil
}

// QueryCards queries the "cards" edge of the SubType entity.
func (st *SubType) QueryCards() *CardQuery {
	return (&SubTypeClient{config: st.config}).QueryCards(st)
}

// Update returns a builder for updating this SubType.
// Note that you need to call SubType.Unwrap() before calling this method if this SubType
// was returned from a transaction, and the transaction was committed or rolled back.
func (st *SubType) Update() *SubTypeUpdateOne {
	return (&SubTypeClient{config: st.config}).UpdateOne(st)
}

// Unwrap unwraps the SubType entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (st *SubType) Unwrap() *SubType {
	tx, ok := st.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubType is not a transactional entity")
	}
	st.config.driver = tx.drv
	return st
}

// String implements the fmt.Stringer.
func (st *SubType) String() string {
	var builder strings.Builder
	builder.WriteString("SubType(")
	builder.WriteString(fmt.Sprintf("id=%v", st.ID))
	builder.WriteString(", name=")
	builder.WriteString(st.Name)
	builder.WriteByte(')')
	return builder.String()
}

// SubTypes is a parsable slice of SubType.
type SubTypes []*SubType

func (st SubTypes) config(cfg config) {
	for _i := range st {
		st[_i].config = cfg
	}
}
