// Code generated by entc, DO NOT EDIT.

package deck

const (
	// Label holds the string label denoting the deck type in the database.
	Label = "deck"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// EdgeCards holds the string denoting the cards edge name in mutations.
	EdgeCards = "cards"
	// Table holds the table name of the deck in the database.
	Table = "decks"
	// CardsTable is the table that holds the cards relation/edge.
	CardsTable = "deck_cards"
	// CardsInverseTable is the table name for the DeckCard entity.
	// It exists in this package in order to avoid circular dependency with the "deckcard" package.
	CardsInverseTable = "deck_cards"
	// CardsColumn is the table column denoting the cards relation/edge.
	CardsColumn = "deck_cards"
)

// Columns holds all SQL columns for deck fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
